### ISSUE TITLE
提示没有权限

### ISSUE THREAD

**Issue by qyzxcswbll** [ygcaicn/docker-deepin#6]
执行安装 docker-deepin install deepin.com.wechat 
提示没有权限
![image](https://user-images.githubusercontent.com/6700057/116498044-6625f580-a8db-11eb-9804-c07d9e9edddd.png)

**Comment by ygcaicn** [comment]
只有图标问题吗？运行正常吗？

**Comment by qyzxcswbll** [comment]
> 只有图标问题吗？运行正常吗？

无法运行
install desktop: /home//.local/share/applications/deepin.com.wechat.desktop
cp: cannot create regular file '/home/deepin/run/deepin.com.wechat.sh': 权限不够

**Comment by qyzxcswbll** [comment]
我尝试使用su root 用户安装，
docker-deepin help 
docker-deepin：未找到命令

**Comment by ygcaicn** [comment]
感谢你的反馈！

目前安装桌面图标的脚本还需要更多的调试。

你可以先按照进阶教程里面的手动执行docker指令使用，我会继续测试桌面图标脚本。

```
docker run -d --name deepin \
    --device /dev/snd --ipc="host"\
    -v $HOME/deepin:/home/deepin \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME:$HOME \
    -e XMODIFIERS=@im=fcitx \
    -e QT_IM_MODULE=fcitx \
    -e GTK_IM_MODULE=fcitx \
    -e DISPLAY=unix$DISPLAY \
    -e AUDIO_GID=`getent group audio | cut -d: -f3` \
    -e VIDEO_GID=`getent group video | cut -d: -f3` \
    -e GID=`id -g` \
    -e UID=`id -u` \
    jachin007/deepin

# docker exec -d deepin tim.sh
docker exec -u deepin -d deepin /opt/deepinwine/apps/Deepin-TIM/run.sh
# docker exec -d deepin wechat.sh
docker exec -u deepin -d deepin   /opt/deepinwine/apps/Deepin-WeChat/run.sh

```

**Comment by ygcaicn** [comment]
> 我尝试使用su root 用户安装，
> docker-deepin help
> docker-deepin：未找到命令

不可以使用sudo，因为所有脚本按照最小权限原则只在家目录活动。

**Comment by qyzxcswbll** [comment]
> > 我尝试使用su root 用户安装，
> > docker-deepin help
> > docker-deepin：未找到命令
> 
> 不可以使用sudo，因为所有脚本按照最小权限原则只在家目录活动。
