### ISSUE TITLE
导出的附件还在docker中

### ISSUE THREAD

**Issue by simon28082** [ygcaicn/docker-deepin#8]
本身是用docker加载的deepin wine，能不能加个目录映射？有时候微信需要附件传输

**Comment by ygcaicn** [comment]
当前用户的home目录都已经映射了呀，~/下的文件都可以直接复制发送

**Comment by simon28082** [comment]
@ygcaicn 感谢，看到了，最开始界面没到这个目录，我以为没有映射，非常感谢
docker模式脱离了宿主机模式非常好
